pimcore:
    properties:
        predefined:
            definitions:
                3286b382-9c69-4986-820c-c25ef101c5f5:
                    name: 'Plan attachment folder - Colur chart'
                    description: 'Default asset folder for plan attachments of type Colur chart.'
                    key: plan_attachment_folder_colur_chart
                    type: text
                    data: '/Color charts'
                    config: ''
                    ctype: object
                    inheritable: false
                    creationDate: 1775538452
                    modificationDate: 1775539037
