doctrine_migrations:
  migrations_paths:
    DoctrineMigrations: '%kernel.project_dir%/migrations'   # keep default if you still use it
    App\Migrations: '%kernel.project_dir%/src/Migrations'    # <-- add this
