imports:
    - { resource: 'local/' }


pimcore:
  workflows:
        workflow:
            label: 'Final product Workflow'
            type: 'state_machine'
            enabled: true
            supports:
                - Pimcore\Model\DataObject\FinalProduct
            audit_trail:
                enabled: false
            places:
                new:
                    label: 'New Final product'
                    color: '#377ea9'
                    permissions:
                        - objectLayout: 'finalProduct1'
                rejected:
                    label: 'Rejected product'
                    color: '#28a013'
                update_components:
                    label: 'Update Components'
                    title: 'Updating components step'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 'finalProduct2' 
                update_colors:
                    label: 'Update Product Colors'
                    title: 'Update the product Colors'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 'finalProduct3'    
                update_finishing:
                    label: 'Update Product Finishing'
                    title: 'Update the product Finishing'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 'finalProduct4'            
                update_pricing:
                    label: 'Update pricing'
                    title: 'Set pricing for markets'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 'finalProduct5'  
                update_medias:
                    label: 'Added medias'
                    title: 'Add product medias'
                    color: '#d9ef36'
                    permissions:
                        - objectLayout: 'finalProduct6'            
                content_prepared:
                    label: 'Content Prepared'
                    title: 'Content ready to publish'
                    color: '#28a013'
                    permissions:
                        - objectLayout: 'finalProduct7'  
            transitions:
                reject_product:
                    from: new
                    to: rejected
                    options:
                        label: 'Reject the product'
                        notes:
                            commentEnabled: true
                            commentRequired: true
                start_processing:
                    from: new
                    to: update_components
                    options:
                        label: 'Start processing the product'
                components_updated:
                    from: update_components
                    to: update_colors
                    options:
                        label: 'Content up-to-date'
                        notes:
                            commentEnabled: true
                            commentRequired: false
                colors_updated:
                    from: update_colors
                    to: update_finishing
                    options:
                        label: 'Colors up-to-date'
                        notes:
                            commentEnabled: true
                            commentRequired: false
                finishing_updated:
                    from: update_finishing
                    to: update_pricing
                    options:
                        label: 'Finishing up-to-date'
                        notes:
                            commentEnabled: true
                            commentRequired: false
                pricing_updated:
                    from: update_pricing
                    to: update_medias
                    options:
                        label: 'Pricing up-to-date'
                        notes:
                            commentEnabled: true
                            commentRequired: false
                medias_updated:
                    from: update_medias
                    to: content_prepared
                    options:
                        label: 'Content is ready to publish'
# IMPORTANT Notice!
# Following there are only some examples listed, for a full list of possible options, please run the following command:
# ./bin/console debug:config pimcore
# you can also filter them by path, eg.
# ./bin/console debug:config pimcore assets
# or even more specific:
# ./bin/console debug:config pimcore assets.image


#### TRANSLATIONS
#    translations:
#        case_insensitive: true

#### FEATURE FLAGS
#    flags:
#        zend_date: true

#### CLASS OVERRIDES EXAMPLES
#    models:
#        class_overrides:
#            'Pimcore\Model\DataObject\News': 'App\Model\DataObject\News'
#            'Pimcore\Model\DataObject\News\Listing': 'App\Model\DataObject\News\Listing'
#            'Pimcore\Model\DataObject\Folder': 'App\Model\DataObject\Folder'
#            'Pimcore\Model\Asset\Folder': 'App\Model\Asset\Folder'
#            'Pimcore\Model\Asset\Image': 'App\Model\Asset\Image'
#            'Pimcore\Model\Document\Page': 'App\Model\Document\Page'
#            'Pimcore\Model\Document\Link': 'App\Model\Document\Link'
#            'Pimcore\Model\Document\Listing': 'App\Model\Document\Listing'


#### CUSTOM DOCUMENT EDITABLES
#    documents:
#        allow_trailing_slash: 'yes'
#        generate_preview: false
#        tags:
#            map:
#                markdown: \App\Model\Document\Tag\Markdown


#### CUSTOM OBJECT DATA TYPES
#    objects:
#        class_definitions:
#            data:
#                map:
#                  myDataType: \App\Model\DataObject\Data\MyDataType


#### ASSET CUSTOM SETTINGS
#    assets:
#        icc_rgb_profile: ''
#        icc_cmyk_profile: ''
#        versions:
#            use_hardlinks: false
#        image:
#            low_quality_image_preview:
#                enabled: false
#                generator: imagick
#            thumbnails:
#                webp_auto_support: false


#### SYSTEM SETTINGS

#    general:
#        timezone: Europe/Berlin
#        path_variable: ''
#        instance_identifier: ''
#    full_page_cache:
#        enabled: false
#        lifetime: null
#        exclude_cookie: ''
#        exclude_patterns: ''
#    httpclient:
#        adapter: Socket # use 'Proxy' for custom proxy configuration
#        proxy_host: ''
#        proxy_port: ''
#        proxy_user: ''
#        proxy_pass: ''
#    email:
#        sender:
#            name: 'Pimcore Demo'
#            email: demo@pimcore.com
#        return:
#            name: ''
#            email: ''

#    applicationlog:
#        mail_notification:
#            send_log_summary: false
#            filter_priority: null
#            mail_receiver: ''
#        archive_treshold: '30'
#        archive_alternative_database: ''

#### SYMFONY OVERRIDES
framework:
#    WHEN RUNNING PIMCORE AND OTHER APPLICATIONS ON SAME DOMAIN, SET SESSION COOKIE NAME TO PROVIDE COLLISION
#    session:
#        name: "PIMCORE_SESSION_ID"
        
#### DEFINE LOCATION OF MANIFEST WHEN WORKING WITH SYMFONY ENCORE
#    assets:
#        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

#### USE CUSTOM CACHE POOL
#    cache:
#        pools:
#            pimcore.cache.pool:
#                public: true
#                default_lifetime: 31536000  # 1 year
#                adapter: cache.adapter.redis_tag_aware
#                provider: 'redis://localhost' # Redis DNS, see: https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html#configure-the-connection

#### USE SESSION HANDLER CONFIGURED IN php.ini
#    session:
#        handler_id: null

#### SYMFONY MAILER TRANSPORTS
#    mailer:
#        transports:
#            main: smtp://user:pass@smtp.example.com:port
#            pimcore_newsletter: smtp://user:pass@smtp.example.com:port

# pimcore_newsletter:
#     default_url_prefix: 'https://my-host.com' # default prefix for your static assets
#     use_specific: false # set true to use the following options for newsletter delivery
#     sender:
#         name: ''
#         email: ''
#     return:
#         name: ''
#         email: ''

