pimcore_data_hub:
    configurations:
        AcetaatColors:
            general:
                active: true
                type: dataImporterDataObject
                name: AcetaatColors
                description: 'Create and update acetate colors, including alternate source codes.'
                group: ''
                path: null
                modificationDate: 1785226960
                createDate: 1759495565
            loaderConfig:
                type: asset
                settings:
                    assetPath: /Datasource Files/Acetate-Colors-alternative.xlsx
            interpreterConfig:
                type: xlsx
                settings:
                    skipFirstRow: true
                    sheetName: Sheet1
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: color
                loadingStrategy:
                    type: attributeWithTrimFallback
                    settings:
                        dataSourceIndex: '0'
                        attributeName: code
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: doNotCreate
                    settings: {  }
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangePublishNew
            processingConfig:
                executionType: sequential
                idDataIndex: '0'
                cleanup:
                    doCleanup: false
                    strategy: delete
            mappingConfig:
                -
                    label: Code
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                mode: both
                            type: trim
                -
                    label: Name
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Type
                    dataSourceIndex:
                        - '5'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: colorType
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Generic
                    dataSourceIndex:
                        - '8'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: genericColor
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: AlternativeCodes
                    dataSourceIndex:
                        - '9'
                    settings:
                        delimiter: ','
                        mode: both
                        glue: "\n"
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: alternateCodes
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                delimiter: ','
                            type: explode
                        -
                            settings:
                                mode: both
                            type: trim
                        -
                            settings:
                                glue: "\n"
                            type: combine
                -
                    label: KEY
                    dataSourceIndex:
                        - '0'
                        - '2'
                    settings:
                        glue: '|'
                        search: /
                        replace: '-'
                        mode: both
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                search: /
                                replace: '-'
                            type: stringReplace
                        -
                            settings:
                                mode: both
                            type: trim
                        -
                            settings:
                                glue: '|'
                            type: combine
                        -
                            settings:
                                mode: both
                            type: trim
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: '03-10-2025 15:00'
            permissions:
                user:
                    -
                        id: 5
                        name: theo_admin
                        read: true
                        update: true
                        delete: true
                role: {  }
            workspaces: {  }
