pimcore_data_hub:
    configurations:
        Colours:
            general:
                active: true
                type: dataImporterDataObject
                name: Colours
                description: ''
                group: ''
                path: null
                modificationDate: 1759497790
                createDate: 1759495565
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: Colours/upload.import
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: "\t"
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: color
                loadingStrategy:
                    type: id
                    settings:
                        dataSourceIndex: '0'
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /
                locationUpdateStrategy:
                    type: staticPath
                    settings:
                        path: /
                publishingStrategy:
                    type: noChangePublishNew
            processingConfig:
                executionType: sequential
                idDataIndex: '0'
                cleanup:
                    strategy: delete
            mappingConfig:
                -
                    label: 'new column'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'new column'
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'new column'
                    dataSourceIndex:
                        - '5'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: colorType
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'new column'
                    dataSourceIndex:
                        - '8'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: genericColor
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: '03-10-2025 15:00'
            permissions:
                user:
                    -
                        id: 5
                        name: theo_admin
                        read: true
                        update: true
                        delete: true
                role: {  }
            workspaces: {  }
