pimcore_data_hub:
    configurations:
        ExampleFamilyJsonImport:
            general:
                active: false
                type: dataImporterDataObject
                name: ExampleFamilyJsonImport
                description: 'Example family importer using docs/datahub-import-examples/sources/json/families.json'
                group: Examples
                path: null
                modificationDate: 1777334400
                createDate: 1777334400
            loaderConfig:
                type: asset
                settings:
                    assetPath: '/Datasource Files/Import Examples/families.json'
            interpreterConfig:
                type: json
                settings:
                    path: ''
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: family
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: family_code
                        attributeName: code
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: findOrCreateFolder
                    settings:
                        dataSourceIndex: import_parent_path
                        fallbackPath: '/Imports/ProductHierarchy/Families'
                locationUpdateStrategy:
                    type: findOrCreateFolder
                    settings:
                        dataSourceIndex: import_parent_path
                        fallbackPath: '/Imports/ProductHierarchy/Families'
                publishingStrategy:
                    type: noChangePublishNew
            processingConfig:
                executionType: sequential
                idDataIndex: family_code
            mappingConfig:
                -
                    label: KEY
                    dataSourceIndex:
                        - family_code
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                search: /
                                replace: '-'
                            type: stringReplace
                        -
                            settings:
                                mode: both
                            type: trim
                -
                    label: Code
                    dataSourceIndex:
                        - family_code
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Name
                    dataSourceIndex:
                        - family_name
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Launch Year
                    dataSourceIndex:
                        - launch_year
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: launchYear
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Launch Period
                    dataSourceIndex:
                        - launch_period
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: launchPeriod
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Working Title
                    dataSourceIndex:
                        - working_title
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: workingTitle
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Description
                    dataSourceIndex:
                        - description
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: description
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Designers Relation
                    dataSourceIndex:
                        - designer_keys
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: designersRelation
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: designer
                                attributeName: key
                                attributeLanguage: ''
                                partialMatch: false
                                loadUnpublished: true
                            type: loadDataObject
                -
                    label: Suppliers
                    dataSourceIndex:
                        - supplier_codes
                    transformationResultType: advancedDataObjectArray
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: suppliers
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: supplier
                                attributeName: code
                                attributeLanguage: ''
                                partialMatch: false
                                loadUnpublished: true
                            type: loadDataObject
                -
                    label: POS Material Products
                    dataSourceIndex:
                        - pos_material_item_codes
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: posMaterialProducts
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: posMaterialProduct
                                attributeName: itemCode
                                attributeLanguage: ''
                                partialMatch: false
                                loadUnpublished: true
                            type: loadDataObject
                -
                    label: Service Part Products
                    dataSourceIndex:
                        - service_part_codes
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: servicePartProducts
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: servicePartsProduct
                                attributeName: code
                                attributeLanguage: ''
                                partialMatch: false
                                loadUnpublished: true
                            type: loadDataObject
                -
                    label: Downloadable Assets
                    dataSourceIndex:
                        - downloadable_asset_keys
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: downloadableAssets
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: downloadableAsset
                                attributeName: key
                                attributeLanguage: ''
                                partialMatch: false
                                loadUnpublished: true
                            type: loadDataObject
                -
                    label: Image Gallery
                    dataSourceIndex:
                        - image_gallery_asset_paths
                    transformationResultType: gallery
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: imageGallery
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: path
                            type: loadAsset
                        -
                            settings: {  }
                            type: gallery
                -
                    label: Attachments
                    dataSourceIndex:
                        - attachment_asset_paths
                    transformationResultType: advancedAssetArray
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: attachments
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: path
                            type: loadAsset
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
