pimcore_data_hub:
    configurations:
        ExampleFrameJsonImport:
            general:
                active: true
                type: dataImporterDataObject
                name: ExampleFrameJsonImport
                description: 'Example frame importer using docs/datahub-import-examples/sources/json/frames.json'
                group: Examples
                path: null
                modificationDate: 1778055139
                createDate: 1777334400
            loaderConfig:
                type: asset
                settings:
                    assetPath: '/Datasource Files/Import Examples/frames.json'
            interpreterConfig:
                type: json
                settings:
                    path: ''
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: finishedProduct
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: frame_code
                        attributeName: code
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: findParent
                    settings:
                        findStrategy: attribute
                        attributeDataObjectClassId: baseProduct
                        attributeName: code
                        attributeLanguage: ''
                        dataSourceIndex: parent_model_code
                        fallbackPath: /Imports/ProductHierarchy/Families
                locationUpdateStrategy:
                    type: findParent
                    settings:
                        findStrategy: attribute
                        attributeDataObjectClassId: baseProduct
                        attributeName: code
                        attributeLanguage: ''
                        dataSourceIndex: parent_model_code
                        fallbackPath: /Imports/ProductHierarchy/Families
                publishingStrategy:
                    type: noChangePublishNew
            processingConfig:
                executionType: sequential
                idDataIndex: frame_code
                cleanup:
                    strategy: unpublish
            mappingConfig:
                -
                    label: KEY
                    dataSourceIndex:
                        - frame_code
                    settings:
                        search: /
                        replace: '-'
                        mode: both
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                search: /
                                replace: '-'
                            type: stringReplace
                        -
                            settings:
                                mode: both
                            type: trim
                -
                    label: Code
                    dataSourceIndex:
                        - frame_code
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Name
                    dataSourceIndex:
                        - frame_name
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Main Color Code'
                    dataSourceIndex:
                        - main_color_code
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: mainColorCode
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Series Code'
                    dataSourceIndex:
                        - series_code
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: seriesCode
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Ecom File Name'
                    dataSourceIndex:
                        - ecom_file_name
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: ecomFileName
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Exchange Code'
                    dataSourceIndex:
                        - exchange_code
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: exchangeCode
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Art Base'
                    dataSourceIndex:
                        - art_base_code
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: baseProduct
                        attributeName: code
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObject
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: artBase
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: baseProduct
                                attributeName: code
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
                -
                    label: 'Item Group'
                    dataSourceIndex:
                        - item_group_numbers
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: itemGroup
                        attributeName: groupNum
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: manyToManyRelation
                        settings:
                            fieldName: itemGroup
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                            overwriteMode: replace
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: itemGroup
                                attributeName: groupNum
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
                -
                    label: Supplier
                    dataSourceIndex:
                        - supplier_code
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: supplier
                        attributeName: code
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObject
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: supplier
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: supplier
                                attributeName: code
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
                -
                    label: 'Composed Colors'
                    dataSourceIndex:
                        - composed_color_codes
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: color
                        attributeName: code
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: manyToManyRelation
                        settings:
                            fieldName: composedColors
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                            overwriteMode: replace
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: color
                                attributeName: code
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
                -
                    label: Components
                    dataSourceIndex:
                        - component_item_codes
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: component
                        attributeName: itemCode
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: manyToManyRelation
                        settings:
                            fieldName: components
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                            overwriteMode: replace
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: component
                                attributeName: itemCode
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
                -
                    label: 'POS Material Products'
                    dataSourceIndex:
                        - pos_material_item_codes
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: posMaterialProduct
                        attributeName: itemCode
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: manyToManyRelation
                        settings:
                            fieldName: posMaterialProducts
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                            overwriteMode: replace
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: posMaterialProduct
                                attributeName: itemCode
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
                -
                    label: 'Service Part Products'
                    dataSourceIndex:
                        - service_part_codes
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: servicePartsProduct
                        attributeName: code
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: manyToManyRelation
                        settings:
                            fieldName: servicePartProducts
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                            overwriteMode: replace
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: servicePartsProduct
                                attributeName: code
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
                -
                    label: 'Downloadable Assets'
                    dataSourceIndex:
                        - downloadable_asset_keys
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: downloadableAsset
                        attributeName: key
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: manyToManyRelation
                        settings:
                            fieldName: downloadableAssets
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                            overwriteMode: replace
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: downloadableAsset
                                attributeName: key
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
                -
                    label: 'Image Gallery'
                    dataSourceIndex:
                        - image_gallery_asset_paths
                    settings:
                        loadStrategy: path
                    transformationResultType: gallery
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: imageGallery
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: path
                            type: loadAsset
                        -
                            type: gallery
                -
                    label: Attachments
                    dataSourceIndex:
                        - attachment_asset_paths
                    settings:
                        loadStrategy: path
                    transformationResultType: assetArray
                    dataTarget:
                        type: manyToManyRelation
                        settings:
                            fieldName: attachments
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                            overwriteMode: replace
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            settings:
                                loadStrategy: path
                            type: loadAsset
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
