pimcore_data_hub:
    configurations:
        SAPItemGroupImport:
            general:
                active: true
                type: dataImporterDataObject
                name: SAPItemGroupImport
                description: ''
                group: ''
                path: null
                modificationDate: 1757910792
                createDate: 1753352126
            loaderConfig:
                type: asset
                settings:
                    assetPath: '/Datasource Files/sap-item-groups.json'
            interpreterConfig:
                type: json
                settings:
                    path: ''
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: itemGroup
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: groupNum
                        attributeName: groupNum
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /SAPItemGroups
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangePublishNew
            processingConfig:
                executionType: sequential
                idDataIndex: groupNum
                cleanup:
                    strategy: unpublish
            mappingConfig:
                -
                    label: groupNum
                    dataSourceIndex:
                        - groupNum
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: groupNum
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: groupName
                    dataSourceIndex:
                        - groupName
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: groupName
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: KEY
                    dataSourceIndex:
                        - groupName
                        - groupNum
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    settings:
                        glue: '|'
                        search: /
                        replace: '-'
                    transformationPipeline:
                        -
                            settings:
                                glue: '|'
                            type: combine
                        -
                            settings:
                                search: /
                                replace: '-'
                            type: stringReplace
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
