pimcore_data_hub:
    configurations:
        SAPSupCatNum:
            general:
                type: graphql
                path: null
                name: SAPSupCatNum
                modificationDate: 1757058182
                createDate: 1753351591
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
