pimcore_data_hub:
    configurations:
        SAPSupplierImport:
            general:
                active: true
                type: dataImporterDataObject
                name: SAPSupplierImport
                description: ''
                group: ''
                path: null
                modificationDate: 1760076519
                createDate: 1753352126
            loaderConfig:
                type: asset
                settings:
                    assetPath: '/Datasource Files/sap-suppliers.json'
            interpreterConfig:
                type: json
                settings:
                    path: ''
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: supplier
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: CardCode
                        attributeName: code
                        language: ''
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /SetupData/SAPSuppliers
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangePublishNew
            processingConfig:
                executionType: sequential
                doArchiveImportFile: true
                idDataIndex: CardCode
                cleanup:
                    strategy: unpublish
            mappingConfig:
                -
                    label: CardCode
                    dataSourceIndex:
                        - CardCode
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: CardName
                    dataSourceIndex:
                        - CardName
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: Country
                    dataSourceIndex:
                        - Country
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: country
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: KEY
                    dataSourceIndex:
                        - CardName
                        - CardCode
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    settings:
                        glue: ' |'
                    transformationPipeline:
                        -
                            settings:
                                glue: ' |'
                            type: combine
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user:
                    -
                        id: 5
                        name: theo_admin
                        read: true
                        update: true
                        delete: true
                role: {  }
            workspaces: {  }
