pimcore_data_hub:
    configurations:
        SAPSupplierImport:
            general:
                type: dataImporterDataObject
                path: null
                name: SAPSupplierImport
                modificationDate: 1757058086
                createDate: 1753352126
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
