pimcore_data_hub:
    configurations:
        TarifCode:
            general:
                type: graphql
                path: null
                name: TarifCode
                modificationDate: 1757058201
                createDate: 1753351591
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
